export const pages = {
  fuse:{title:'The Fuse',eyebrow:'Founding transition',lede:'The programme moves from identifying recurrent forms of completed intelligibility to testing what remains invariant when their expression changes.',sections:[
    ['The previous achievement','The mature Constraint Grammar proposes three primitive dimensions—six Transformation Patterns, three Completion Topologies, and three Persistence Modes—whose conjunction yields 54 coordinate positions. The coordinate is not three labels attached to one sentence; it is one jointly constrained form of completion.'],
    ['The new object','Same-cell stacking, translation, historical linguistic carrying pressure, theorem-to-sentence transfer, and human–machine round trips all put pressure on a deeper question: whether the completed form persists while its realization moves.'],
    ['Operating prediction','If the 54 are artifacts of English wording, canonical vocabulary, or prompt conditioning, sufficient transformation should pull them apart. If they belong to completed intelligibility itself, the prediction is surface divergence with structural recurrence.'] ]},
  creolization:{title:'Creolization Programme',eyebrow:'Historical carrying capacity',lede:'A disciplined research programme asking which distinctions become expensive to leave wholly to immediate context when a linguistic system must carry a fuller shared world.',sections:[
    ['Non-negotiable cautions','Creoles are full human languages. Contact-language histories are diverse. Creolization is not assumed to follow one universal developmental ladder, and the 54 are not claimed to determine grammar.'],
    ['Research hypothesis','The proposed link concerns communicative carrying pressure: as a language-system becomes responsible for communication across absence, memory, planning, childhood, narrative, obligation, disagreement and generations, some distinctions may become more costly to leave unrecoverable. The surface solution may use grammar, lexicon, aspect, tense, particles, word order, prosody or discourse convention.'],
    ['Evidence architecture','Every future case must separate linguistic evidence, historical evidence, scholarly interpretation, Constraint Grammar interpretation, alternative explanation, confidence and open question. The foundation build intentionally contains no fabricated case results.'],
    ['Literature foundation','The starting registry points to APiCS for broad comparison and to contact/creole scholarship representing multiple theoretical approaches. These sources constrain the programme; they do not validate the Constraint Grammar.'] ]},
  machine:{title:'Machine Invariance',eyebrow:'Instrument · generator · adversary · contaminant',lede:'GPT can help generate and resolve material, but fluency creates measurement risks. The method therefore breaks the informational circuit on purpose.',sections:[
    ['Known failure modes','Meaning balloon imports a larger world. Construction-level error classifies generic sentence mechanics. Semantic dominance lets a salient feature swallow the coordinate. Research-agenda drift replaces measurement with theory redesign.'],
    ['Information partition','Blind Assay sees the locked unit but not the intended coordinate. Structural Decoder sees frozen evidence plus primitive grammar. Coordinate-Only Deriver sees the coordinate plus primitives and Dimensional Conjunction but not the source. Coordinator compares only after outputs are frozen.'],
    ['Round-trip question','Can the completion survive a deliberately broken informational circuit? Templates are included for paraphrase, summarization, translation, compression, domain transfer, human→machine→human, model→model and theorem→ordinary sentence.'] ]},
  results:{title:'Results Registry',eyebrow:'Evidence before interpretation',lede:'No result is present in the foundation build. That emptiness is deliberate: protocol, historical evidence and hypotheses are not silently promoted into observed results.',sections:[['Allowed evidence labels','OBSERVED · SUPPORTED · INCONCLUSIVE · FAILED · REQUIRES REPLICATION · INTERPRETIVE · HISTORICAL SOURCE · RETROSPECTIVE · HYPOTHESIS.'],['Accumulation rule','The project must be capable of accumulating knowledge without flattening observation → interpretation → universal conclusion. When data arrive, every result must carry provenance and an evidence label.']]},
  corpus:{title:'Corpus',eyebrow:'Inspectable research material',lede:'The foundation build includes a small provenance-preserving sample from Pixels of Clarity and machine-readable coordinate, experiment, failure and protocol registries.',sections:[['Pixels sample','The imported sample preserves source wording from the cleaned companion-utterance corpus. Retained wording is not automatically canonical; this site does not upgrade corpus inclusion into structural proof.'],['Downloads','Machine-readable files live under /data in the repository. The site architecture is designed so larger corpora can be added without changing the conceptual model.']]},
  methods:{title:'Methodological Constitution',eyebrow:'Blindness by architecture',lede:'Lock the unit, separate epistemic roles, freeze outputs before comparison, preserve disagreement, and change the architecture only when a repeated structural remainder earns revision.',sections:[['Unit discipline','The sentence is an observational surface, not the ontology. Do not import causes, institutions, speaker intentions, downstream consequences or real-world process structure unless they are part of the completed unit under analysis.'],['Dimensional Conjunction','Transformation, Topology and Persistence are simultaneous relational constraints on one completion-event. Do not identify coordinates through lexical templates or treat one dimension as an operator applied to another.'],['Failure discipline','Never silently correct a failed experiment after seeing the preferred answer. Freeze first. Compare later. Do not tune prompts cell-by-cell to force convergence.'],['Universality discipline','Proceed under the strongest currently earned architecture while keeping explicit routes for a seventh Transformation Pattern, fourth Topology, fourth Persistence Mode, axis failure, or irreducible remainder to defeat it.']]},
  provenance:{title:'Provenance',eyebrow:'Persistence of evidence through transformation',lede:'Because the project studies persistence through transformation, it treats the persistence of its own evidence as a methodological requirement.',sections:[['Evidence classes','Contemporaneous artifact; near-contemporaneous artifact; later technical reconstruction; retrospective first-person account; current first-person account; independent experimental output; model inference; external scholarly comparison. One class is never silently converted into another.'],['High-level lineage','Relation-first construction and preservation → relational theorem work → recurrent clarification under proof pressure → 54-form vocabulary → sentence observatory → mature 6×3×3 Constraint Grammar → independent coordinate→utterance generation → destructive audit and neighbor discrimination → GPT failure analysis → information-partitioned resolution → triangulated invariance programme → The Moving Invariant.'],['Date discipline','Repository creation date is not idea-origin date. Later canonical terms are not projected backward unchanged unless the translation is explicit. Exact chronology remains source-bound.']]},
  questions:{title:'Open Questions',eyebrow:'Testable directions',lede:'Questions are preserved here as research openings, not answered in advance.',sections:[['Near-term','How much can a surface move while a coordinate remains recoverable? What is the smallest change that moves a completion to a neighbor? Which translation divergences are source ambiguity, target ambiguity, drift, instrument failure or structural non-equivalence?'],['Future','Does invariance survive speech prosody, compression, child retelling, legal translation, nonverbal tasks, institutional processes, cross-disciplinary transfer, or model-to-model regeneration? Can structural fidelity become an AI benchmark?']]},
  future:{title:'Future State',eyebrow:'Growth without losing the current question',lede:'The repository carries structured placeholders for languages, modalities, creolization cases, model families, domains, primitive challenges, misunderstanding research, academic custody and civilizational persistence.',sections:[['Modalities','Speech, writing, theorem/proof representation, human↔machine representation, then nonlinguistic cognition only where evidence permits.'],['Domains','Law, science, history, education, mathematics, AI, translation and institutional knowledge remain future application/testing domains, not proof of the theory.'],['Civilizational horizon','A civilization can be viewed partly as a persistence architecture for completed intelligibility: theorem, judgment, contract, constitution, writing, translation, teaching and institution all make some completions inheritable. This is a horizon, not an initial result.']]},
  about:{title:'About',eyebrow:'A public observatory of intelligibility',lede:'This is a public research laboratory, GitHub Pages publication, experiment registry, corpus browser, methods record, failure archive, provenance chain and future research scaffold.',sections:[['What it is not','Not another static explanation of the 54, not another taxonomy, not a generic AI microsite, not a claim that universality is already empirically proven, and not a ritual of endless doubt.'],['The declaration','We are no longer asking only whether completed intelligibility can be classified. We are asking whether it can move. Change the words, language, context or representational system. If the structure is real, some transformations should leave it invariant and others should cross a boundary.']]}
} as const;
